export const MODAL_TEXT = {
	title: "Agregar jugador",
	nameInput: {
		formControlName: "name",
		fullWidth: true,
		errorHelper: "Campo obigatorio",
		placeholder: "",
		size: "small",
		type: "text",
		label: "Nombre",
	},
	lastInput: {
		formControlName: "last",
		fullWidth: true,
		errorHelper: "Campo obigatorio",
		placeholder: "",
		size: "small",
		type: "text",
		label: "Apellido",
	},
	imageInput: {
		formControlName: "image",
		fullWidth: true,
		errorHelper: "Campo obigatorio",
		placeholder: "https://....",
		size: "small",
		type: "text",
		label: "Imagen",
	},
	positionInput: {
		formControlName: "position",
		fullWidth: true,
		errorHelper: "Campo obigatorio",
		placeholder: "Ingresa posición",
		size: "small",
		type: "text",
		label: "Posición",
	},
	actionAdd: "Agregar",
	errorsInput: {
		required: "Este campo es obligatorio",
		min: "Valor mínimo: ",
	},
};
